const db = require('../models');
const Comment = require('../models').Comment;

Comment.sync({force: true})
.then(() => db.sequelize.sync())
//add the following post to the database:
.then(() => Comment.bulkCreate([
  {comment: 'The way his hair fades into the sky.', PostId: 6},
  {comment: 'Use a dry brush and just pull it', PostId: 6},
  {comment: 'There are no mistakes, just happy little accidents', PostId: 6},
  {comment: "We'll just put some bushes here, look at that, little doers.", PostId: 6},
  {comment: "This thread just keeps getting more and more pure.", PostId: 6},
  {comment: "Let's get crazy.", PostId: 6},
  {comment: "It sounds sappy, but when Bob said stuff like that I found it really comforting", PostId: 6},
  {comment: "He really, really enjoyed doing that", PostId: 6},
  {comment: "My 3 year old daughter loves Bob Ross, and recently she has started doing this with her watercolor brush and easel", PostId: 6},
  {comment: "Not enough phthalo blue.", PostId: 6},
  {comment: "I can't tell where Bob Ross ends and heaven begins", PostId: 6},
  {comment: "57550 calories is what you're wondering.", PostId: 1},
  {comment: "Correct. If you burn 2.5k calories a day, you'd end up burning an excess 17,450 calories in a month, which is just about 5 pounds", PostId: 1},
  {comment: "Brushing your teeth is exercise, right?", PostId: 1},
  {comment: "So is lifting burgers and beer.", PostId: 1},
  {comment: "I lost a lot of weight this year mostly eating fast food burgers and pizza. It was a pretty good diet.", PostId: 1},
  {comment: "Did you have to amputate an arm or a leg?", PostId: 1},
  {comment: "16 curls", PostId: 1},
  {comment: "16 oz curly fries", PostId: 1},
  {comment: "It brings back the best of JavaScript in a modern component oriented way", PostId: 2},
  {comment: "I wish more people cared about finding the 'right' way to do things haha. Well said!", PostId: 2},
  {comment: "I know I don't have to. I was just troubled by the fact that you propose to create a view layer component just in order to fetch data.", PostId: 2},
  {comment: "If you like the observable pattern to subscribe components to data, you will enjoy mobservable :)", PostId: 2},
  {comment: "Have you received any feedback, positive or negative from Apple about the long-term viability of using the JavaScriptCore as a means of powering ReactNative?", PostId: 9},
  {comment: "As of now, how does React Native fare to the variability of devices in the Android ecosystem? This is referring to things like screen dimensions, API differences between versions of the OS, etc.", PostId: 9},
  {comment: "Save yourself a lot of headaches and use react-motion or animated.", PostId: 7},
  {comment: "I'd be hard to watch this talk: https://www.youtube.com/watch?v=1tavDv5hXpo and not become immediately impressed by react-motion.", PostId: 7},
  {comment: "I've done a lot with CSS animations and adding/removing classes. If you have a specific animation you need help on, maybe I could speak to that.", PostId: 7},
  {comment: "I need to slide menu from right to left. http://imgur.com/a/BtHJG", PostId: 7},
  {comment: "Due to the fact that elements are added/removed from the DOM you need to use some helpers to add/remove various 'state' classes.", PostId: 7},
  {comment: "I've been using velocity-react for mount/unmount animations.", PostId: 7},
  {comment: "I'd also like some more detailed documentation on ReactTransitionGroup. Wish I could find some examples.", PostId: 7},
  {comment: "This is the best. React Comprehensive Guide", PostId: 11},
  {comment: "Thanks! This is exactly what I was looking for, something that goes over the concepts with a real project example and also tooling (like gulp and Browserify in this case).", PostId: 11},
  {comment: "This looks good so far but I can't help but notice its only half complete, and was last updated in April. The last two planned articles might not be as crucial, but routing will be if you plan on making a single page app.", PostId: 11},
  {comment: "Hi pdizz. I wrote the series above. React Router is going through a rather extensive API update right now. So I've been waiting until they've at least put the new router in Beta before I write the next article. If it's not out in the next month I'll write it with the 'old' router.", PostId: 11},
  {comment: "I use react-infinite-scroll which works very well.", PostId: 12},
  {comment: "I'll take a look at that. It does seem to do what I need it to do", PostId: 12},
  {comment: "is this library up to date?", PostId: 12},
  {comment: "Title should be: '9 things React.js beginners don't need to worry about just yet.'", PostId: 13},
  {comment: "Yes, and totally doable with react-redux and the connect function. In fact if you watch the egghead.io redux tutorials thats what Dan Abramov suggests you do.", PostId: 13},
  {comment: "Cool, I always watched the video tutorial also recommended to me, and that made it quite a bit clearer. Luckily I was mistaken, not the rest of the Internet!", PostId: 13},
  {comment: "Redux has an example app that uses data fetching right in the repo: https://github.com/reactjs/redux/tree/master/examples/real-world", PostId: 14},
  {comment: "SHE THINKS I'M CUTE!! SHE THINKS I'M CUUUUUUUTE!!", PostId: 4},
  {comment: "What a timely reference.", PostId: 4},
  {comment: "What is this a reference to? I can't think of the movie.", PostId: 4},
  {comment: "Rudolf the Pimpin' Deer.", PostId: 4},
  {comment: "SHE LIKES MY SPARK!", PostId: 4},
  {comment: "woa, really really cute. that is great ! ^ ^", PostId: 4},
  {comment: "It looks like the dog on the right forgot what love felt like until this moment.", PostId: 4},
  {comment: "MY PERSON IS DYING!!!! MUST RUN TO RESCUE!!! MUST SAVE MY PERSON!!!!!!!!!!!", PostId: 5},
  {comment: "Pretty sure this is 100% what goes through her head xD", PostId: 5},
  {comment: "They're very intelligent too!", PostId: 5},
  {comment: "I know I'm super late to the party, but dogs will actually sneeze at eachother to show that they want to play. I think some dogs interpret human sneezes the same way.", PostId: 5},
]))
.catch((err) => console.log(err));
